version: 2
updates:
  - package-ecosystem: "dotnet"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: ["develop", "main"]
    labels:
      - "dependencies"
