name: Deploy

on:
  workflow_dispatch:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Tests
      run: dotnet test -c Release --no-restore

    - name: Pack
      run: dotnet pack -c Release --no-restore

    - name: Deploy
      run: dotnet msbuild TCSystem.sln -t:NugetPush -p:Configuration=Release
